name: Promote to Prod

on:
  workflow_dispatch:
    inputs:
      sourceDigest:
        description: "Digest to promote (e.g., sha256:abcd...)"
        required: true

env:
  STAGE_REPO: docker.io/devopscube/web-app-stage
  PROD_REPO: docker.io/devopscube/web-app-prod

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup Trivy
      uses: aquasecurity/setup-trivy@v0.2.0
      with:
        cache: true
        version: v0.69.3

    - name: Run Trivy vulnerability scan
      uses: aquasecurity/trivy-action@0.33.1
      with:
        scan-type: image
        image-ref: '${{ env.DEV_REPO }}@${{ github.event.inputs.sourceDigest }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        skip-setup-trivy: true

    - name: Install crane
      run: |
        go install github.com/google/go-containerregistry/cmd/crane@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Promote to prod repo
      run: |
        digest="${{ github.event.inputs.sourceDigest }}"
        echo "${{ steps.meta.outputs.tags }}" | while read -r TAG; do
          crane copy "${{ env.STAGE_REPO }}@$digest" "$TAG"
        done

    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.0.0

    - name: Sign prod image
      env:
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      run: |
        PROD_DIGEST=$(crane digest $(echo "${{ steps.meta.outputs.tags }}" | head -1))
        cosign sign --yes \
          --key env://COSIGN_PRIVATE_KEY \
          "${{ env.PROD_REPO }}@${PROD_DIGEST}"